name: lumilens
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publishing
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1  # Updated to the latest version
  firebase_auth: ^4.19.4  # Updated to the latest version
  cloud_firestore: ^4.0.1
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.0
  http: ^0.13.3
  video_player: ^2.2.14
  wakelock: ^0.6.2
  carousel_slider: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

